# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "nokogiri", "~> 1.10"

gem "pry", "~> 0.13.1"

gem "faraday", "~> 1.0"

gem "excon", "~> 0.75.0"

gem "concurrent-ruby", "~> 1.1"
