jruby:
	docker run --rm -it -v $(shell pwd):/workspace -w /workspace jruby:9.2.11.1-jdk14 bash

ruby:
	docker run --rm -it -v $(shell pwd):/workspace -w /workspace ruby:2.7.1 bash

truffleruby:
	docker run --rm -it -v $(shell pwd):/workspace -w /workspace tsutorm/truffleruby:graalvm-ce-20.2.0-dev bash

